### ISSUE TITLE
VirusTotal Scan

### ISSUE THREAD

**Issue by bufce2010** [Goojoe/LTSC-ADD-Microsoft-Store#1]
I'm not an advanced user and those threats scared me:
[https://www.virustotal.com/gui/file/eb0651f8d6d13a3d1f963aa54c50d0f85db715b977b6b34f72fda1e4c12a5ff5?nocache=1](url)

![image](https://github.com/Goojoe/LTSC-ADD-Microsoft-Store/assets/50169186/9dab0bd0-b4b2-41ff-a80d-a0e3643edc75)

**Comment by Goojoe** [comment]
This was compiled using PyInstaller. If you're really concerned, you can use another method: manually install the pip package and execute the command, which is quite simple.

**Comment by bufce2010** [comment]
> This was compiled using PyInstaller. If you're really concerned, you can use another method: manually install the pip package and execute the command, which is quite simple.

Yes, You are right, Thank you for your work and reply.
