### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by zq092988** [Goojoe/LTSC-ADD-Microsoft-Store#10]
怎么安装啊

**Comment by Goojoe** [comment]
https://lmstfy.net/?q=5oCO5LmI5a6J6KOFcHl0aG9u5bm26L+Q6KGM6ISa5pys

**Comment by zq092988** [comment]
> [https://lmstfy.net/?q = 5 oco 5 LMI 5 a6j 6 kof CHL 0 ag 9 u 5 BM 26 l+q 6 KGM 6 isa 5 pys](https://lmstfy.net/?q=5oCO5LmI5a6J6KOFcHl0aG9u5bm26L+Q6KGM6ISa5pys)

环境弄好了，不会安装

**Comment by Goojoe** [comment]
解压，文件路径内打开CMD，输入我给的命令，按提示操作

**Comment by Goojoe** [comment]
没绷住，你能不能自己先搜索一下再来问我

**Comment by zq092988** [comment]
搜索找不到答案，没办法！！！

**Comment by Goojoe** [comment]
这不是理由！！！！

**Comment by zq092988** [comment]
咱就说到现在我也没搞明白怎么安装

**Comment by Goojoe** [comment]
你截图也不给，描述也不会描述，我也不知道怎么安装了

**Comment by zq092988** [comment]
图怎么发

**Comment by zq092988** [comment]
![Uploading E1CCYX7BXEJ1~XA%K]S%9(K.png…]()

**Comment by zq092988** [comment]
![E1CCYX7BXEJ1~XA%K S%9(K](https://github.com/Goojoe/LTSC-ADD-Microsoft-Store/assets/150695095/11904b2b-afbf-412d-b23b-50149972f59d)

**Comment by Goojoe** [comment]
你这不是能用吗？？你不会输入命令吗？？？

**Comment by zq092988** [comment]
不会啊

**Comment by Goojoe** [comment]
好好好，自己研究吧，这不会，那不看，搜索不会搜索，搜索后又看不懂

**Comment by zq092988** [comment]
解压包里哪个是命令

**Comment by Goojoe** [comment]
你是看不懂主页中文文档还是怎么样

**Comment by zq092988** [comment]
这个网站我都没玩明白，我应该是会弄了
