### ISSUE TITLE
Can u make english version please?

### ISSUE THREAD

**Issue by U-ruRu** [Goojoe/LTSC-ADD-Microsoft-Store#2]
Thx in advance.

![shot](https://github.com/Goojoe/LTSC-ADD-Microsoft-Store/assets/97646117/2d2b316d-24b6-4955-a2d3-a80b2b47172f)

**Comment by Goojoe** [comment]
Of course, it is possible. Initially, this program only supported Chinese, and I was not aware that there were English users using it. I will support English as soon as possible. In the meantime, you can install it using pip and then open and use it with the Windows terminal, which supports the UTF-8 character set perfectly.

**Comment by Goojoe** [comment]
Hey, I've supported English
