### ISSUE TITLE
Doesn't works on Win10 1507

### ISSUE THREAD

**Issue by hooddy** [Goojoe/LTSC-ADD-Microsoft-Store#5]
`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'
Press any key to continue. . .`

Windows 10 x64 1507

**Comment by vincentlarkin** [comment]
The README.md says it only works on 1807 and above.1507 is an incredibly unsecure version of Windows 10 anyways, you shouldn't be on it.

**Comment by Goojoe** [comment]
This is a program error, but as mentioned above, you cannot install the Microsoft store even if the program runs normally
