### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Maxhem2** [Goojoe/LTSC-ADD-Microsoft-Store#7]
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Windows cannot install package Microsoft.WindowsStore_22309.1401.5.0_x64__8wekyb3d8bbwe because this package is not
compatible with the device. The package requires OS version 10.0.18363.0 or higher on the Windows.Mobile device
family. The device is currently running OS version 10.0.17763.4377.
NOTE: For additional information, look for [ActivityId] 9ceba636-033d-0001-4d21-f19c3d03da01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 9ceba636-033d-0001-4d21-f19c3d03da01
At C:\Users\Administrator\Desktop\LTSC-ADD-Microsoft-Store-master\LTSC-ADD-Microsoft-Store-master\Download\install_ms-s
tore.ps1:3 char:1
+ Add-AppxPackage *.Msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Admini...bbwe.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by Goojoe** [comment]
https://github.com/Goojoe/LTSC-ADD-Microsoft-Store/issues/5
